
export default [
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
    {
        title:'set video playback speed with javascript',
        category:'javascript',
        description:'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression....',
        img:'https://picsum.photos/200/300',
    },
]